// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 25.1 (Build Build 1129 10/21/2025)
// Created on Sat Apr 18 15:03:54 2026

alert2leds alert2leds_inst
(
	.AL3_in(AL3_in_sig) ,	// input  AL3_in_sig
	.AL2_in(AL2_in_sig) ,	// input  AL2_in_sig
	.AL1_in(AL1_in_sig) ,	// input  AL1_in_sig
	.AL0_in(AL0_in_sig) ,	// input  AL0_in_sig
	.led3_out(led3_out_sig) ,	// output  led3_out_sig
	.led2_out(led2_out_sig) ,	// output  led2_out_sig
	.led1_out(led1_out_sig) ,	// output  led1_out_sig
	.led0_out(led0_out_sig) 	// output  led0_out_sig
);

